### PR TITLE
Remove QuickDialingView reference

### PR DESCRIPTION
**Pull request by esthcarelle**
### Quick Description of What this is about

- Removed QuickDialingActivity
- Removed QuickDialingView navigation reference
- Removed QuickDialingView string resources

### CODE REVIEW

**Review by cedricbahirwe — CHANGES_REQUESTED** [review]
It sesms that `quick dial` reference is still on the home screen and `NavRoute`, as well as `string.xml`

**Comment by esthcarelle** [comment]
@cedricbahirwe the ticket only mentioned QuickDialingView

**Comment by cedricbahirwe** [comment]
> @cedricbahirwe the ticket only mentioned QuickDialingView , that s why I left out the quick dial

Yes, also mentioned removing the reference to it, which are still present in the aforementioned files..
For instance, the app would crash now if you tried to navigate to that quick dialing view since the home screen has a button that tries to navigate there

**Comment by esthcarelle** [comment]
@cedricbahirwe so you mean the QuickDialingView is also referenced as quickdial, one of the composable has that name?
PS: I am winning this argument

**Comment by cedricbahirwe** [comment]
> @cedricbahirwe so you mean the QuickDialingView is also referenced as quickdial, one of the composable has that name?
> 
> PS: I am winning this argument

By Reference, I meant everything(code) related to QuickDialingView, you can't just remove it then leave strings related to it or navigation code related to it

**Review by cedricbahirwe — APPROVED** [review]

**Comment by esthcarelle** [comment]
@cedricbahirwe the ticket should have your answer as description , cause I thought composable were supposed to have the same name as QuickDialingView, quickdial might be something else not even related with the QuickDialingView, that s why having both names would have helped
PS: You created these codes which means my understanding of the naming convention is still limited

**Comment by esthcarelle** [comment]
let me merge it before you come back with another argument

**Comment by cedricbahirwe** [comment]
> > @cedricbahirwe so you mean the QuickDialingView is also referenced as quickdial, one of the composable has that name?
> > PS: I am winning this argument
> 
> By Reference, I meant everything(code) related to QuickDialingView, you can't just remove it then leave strings related to it or navigation code related to it

Roger that, thanks!

**Pull request merged**
