### PR TITLE
Dependencies upgrade

### PR DESCRIPTION
**Pull request by cedricbahirwe**
- Upgrade Jetpack dependencies
- Upgrade Gradle version
- Upgrade Kotlin Version

- Comment unused code and models
- Remove deprecated APIs usage

### CODE REVIEW

**Review by esthcarelle — CHANGES_REQUESTED** [review]
It looks like some changes you made in the previous PR are reflected here , did you make the changes twice on purpose?

**Comment by cedricbahirwe** [comment]
No, this one is not ready to be reviewed, I'll finish it up today, and add you for review

**Comment by cedricbahirwe** [comment]
I've updated this PR, please check and let me know, also, review the `gradle` file(s), I'm not an expert i the domain, but i did what I could,

**Comment by cedricbahirwe** [comment]
@esthcarelle , were you able to check this?

**Pull request merged**
